trigger:
- main



pool:
  vmImage: 'ubuntu-latest'



steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'



- script: |
    npm ci
  displayName: 'npm ci'
- script: |
    npm test
  displayName: 'npm test'
# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '*.trx'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/bin/**
      **/routes/**
      app.js
      package.json
      package-lock.json
      **/node_modules/**
    TargetFolder: './npm'