name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Running workflow
        run: |
         npm ci
         npm run build --if-present
         npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v5
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
      - name: Build an Artifact
        uses: actions/upload-artifact@v5
